#include "rcc.h"


void RCC_GPIOA_CLK_ENABLE(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
}

void RCC_GPIOB_CLK_ENABLE(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
}

void RCC_GPIOC_CLK_ENABLE(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
}

void RCC_GPIOD_CLK_ENABLE(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPDEN;
}

void RCC_GPIOE_CLK_ENABLE(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_IOPEEN;
}

void RCC_USART1_CLK_ENABLE(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;
}
